import type { ReceiptCertificateData } from "./receipt-certificate";

export const receiptCertificateSampleData: ReceiptCertificateData = {
  organization: {
    name: "Toko Emas Asih Jaya",
    timezone: "Asia/Jakarta",
    currency: "IDR",
  },
  outlet: {
    id: "preview-outlet",
    code: "UTAMA",
    name: "Pasar Bantar Gebang",
    address: "Pasar Bantar Gebang, LT dasar Blok H8, H9, H10",
    phone: "0821 1806 8889",
  },
  register: {
    code: "POS-01",
    name: "Kasir Utama",
  },
  cashier: {
    fullName: "Hanita",
  },
  customer: {
    fullName: "Kiki",
    phone: "088881100209",
  },
  sale: {
    id: "preview-sale",
    invoiceNumber: "ORD/06/2026/440",
    status: "completed",
    subtotalAmount: "7185000",
    discountAmount: "0",
    additionalFeeAmount: "0",
    totalAmount: "7185000",
    completedAt: new Date("2026-06-25T07:30:00.000Z"),
    notes: "Preview sandbox desain nota dan surat jaminan.",
  },
  items: [
    {
      lineNumber: 1,
      listPriceAmount: "3685000",
      discountAmount: "0",
      finalPriceAmount: "3685000",
      snapshot: {
        sku: "AJ-ITEM-679109",
        barcode: "679109",
        qrValue: "679109",
        serialNumber: "679109",
        productCode: "GLG-CARTIER-OVAL",
        productName: "Gelang Cartier Oval",
        categoryName: "Gelang",
        weightGram: "3.76",
        purityPercent: "30",
        exchangePurityPercent: "30",
        size: null,
        color: "Gold",
        gemstone: null,
        sellingAmount: "3685000",
      },
    },
    {
      lineNumber: 2,
      listPriceAmount: "2150000",
      discountAmount: "0",
      finalPriceAmount: "2150000",
      snapshot: {
        sku: "AJ-ITEM-882104",
        barcode: "882104",
        qrValue: "882104",
        serialNumber: "882104",
        productCode: "CCN-KAWIN-POLOS",
        productName: "Cincin Kawin Polos",
        categoryName: "Cincin",
        weightGram: "2.15",
        purityPercent: "75",
        exchangePurityPercent: "75",
        size: "14",
        color: "Gold",
        gemstone: null,
        sellingAmount: "2150000",
      },
    },
    {
      lineNumber: 3,
      listPriceAmount: "1350000",
      discountAmount: "0",
      finalPriceAmount: "1350000",
      snapshot: {
        sku: "AJ-ITEM-991022",
        barcode: "991022",
        qrValue: "991022",
        serialNumber: "991022",
        productCode: "KLN-NURI-ANAK",
        productName: "Kalung Nuri Anak",
        categoryName: "Kalung",
        weightGram: "1.5",
        purityPercent: "37.5",
        exchangePurityPercent: "37.5",
        size: null,
        color: "Gold",
        gemstone: null,
        sellingAmount: "1350000",
      },
    },
  ],
  verification: {
    token: "preview-token",
    url: "http://localhost:3000/v/preview-token",
  },
  payments: [
    {
      method: "cash",
      provider: "Cash",
      amount: "7185000",
      providerReference: null,
      paidAt: new Date("2026-06-25T07:30:00.000Z"),
      metadata: {
        receivedAmount: 7200000,
        changeAmount: 15000,
        methodLabel: "Cash",
      },
    },
  ],
};
